# docker-compose file for building the base images
version: '3.4'

services:
  vivarium:
    container_name: bassenji
    build:
      context: build/bassenji
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: jupyter/scipy-notebook
    ports:
      - 7890:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /data/Workspace/SysMo/vivarium/vivarium-sysmo/notebooks:/home/jovyan/work

  scanpy:
    container_name: scanpy
    build:
      context: build/scanpy
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: leanderd/single-cell-analysis:210114
    ports:
      - 8888-8892:8888-8892
    command:
      - sleep
      - "infinity"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /data/Workspace/SysMo/ENCODE/notebooks:/root/host_home/notebooks
      - /data/Workspace/SysMo/ENCODE/jenie:/root/host_home/pylibs/jenie
      - /data/Workspace/SysMo/ENCODE/external:/root/host_home/external
