version: '3.4'

services:
  cellicium:
    container_name: cellicium
    build:
      context: build/cellicium
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: jupyter/scipy-notebook:8d32a5208ca1
    ports:
      - 8888-8892:8888-8892
    # command:
    #   - sleep
    #   - "infinity"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      PYTHONPATH: "/home/jovyan/pylibs"
    volumes:
      - /data/Workspace/SysMo/ENCODE/notebooks:/home/jovyan/notebooks
      - /data/Workspace/SysMo/ENCODE/cellicium:/home/jovyan/pylibs/cellicium
      - /data/Workspace/SysMo/ENCODE/external:/home/jovyan/external
