version: '3.4'

services:
  cellicium:
    container_name: cellicium
    build:
      context: build/cellicium
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: jupyter/scipy-notebook:8d32a5208ca1
    ports:
      - 8888-8892:8888-8892
      - 6006:6006
    # command:
    #   - sleep
    #   - "infinity"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      PYTHONPATH: "/home/jovyan/pylibs"
      GRANT_SUDO: "yes" # Only works if user set to root
    # user: root
    volumes:
      - ${ABS_TOPLEVEL}/notebooks:/home/jovyan/notebooks
      - ${ABS_TOPLEVEL}/cellicium:/home/jovyan/pylibs/cellicium
      - ${ABS_TOPLEVEL}/external:/home/jovyan/external
      - ${ABS_TOPLEVEL}/../NeurIPS:/home/jovyan/neurips

  oath2:
    container_name: oath2
    build:
      context: build/oath2
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
