bassenji/build:
	docker-compose build bassenji

bassenji/up:
	docker-compose up bassenji

bassenji/bash:
	docker-compose exec bassenji /bin/bash

scanpy/build:
	docker-compose build scanpy

scanpy/up:
	docker-compose up scanpy

scanpy/bash:
	docker-compose exec scanpy /bin/bash

scrnaseq-sanger/build:
	docker-compose build scrnaseq-sanger

scrnaseq-sanger/up:
	docker-compose up scrnaseq-sanger

scrnaseq-sanger/bash:
	docker-compose exec scrnaseq-sanger /bin/bash
